version: "3"
services:
  businessman:
    build:
      dockerfile: src/backend/Dockerfile
      context: .
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn settings.wsgi:application --bind 0.0.0.0:8888"
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.businessman.rule=Host(`businessman.localhost`)"
      - "traefik.http.services.businessman.loadbalancer.server.port=8888"
    networks:
      - web
    environment:
      SECRET_KEY: django-insecure-oe_gb=p9(u7p4+p0i)fz7ted-toqunxt(nzwqsi!cvdg%v=u*c
      POSTGRES_DB: businessman
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
volumes:
  static:
  media:
networks:
  web:
    external: true